version: '3.8'

services:
  app:
    build: .
    container_name: product-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION_URL: mongodb://mongo:27017/nestdb
      CONTENTFUL_ACCESS_TOKEN: myAccessToken
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
